name: E2E Testing with Cypress on Chrome

on:
  push:
    branches:
      - main

jobs:
  testing-with-chrome:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: e2e-test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      # - name: Install dependencies
      #   run: apt-get update && apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          project: .
          browser: chrome
          build: npm run db:push && npm run db:seed && npm run build
          start: npm run start
          wait-on: "http://localhost:3000"
        env:
          DATABASE_URL: "postgres://postgres:123456@localhost:5432/e2e-test"
