name: E2E Testing with Cypress on Chrome

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: e2e-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/e2e-test

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      # run the migration in the test database
      - run: npm run db:push
      - run: npm run db:seed

      # run Cypress testing.
      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          project: .
          browser: chrome
          build: npm run build
          start: npm run start
          wait-on: "http://localhost:3000"
        env:
          DATABASE_URL: "postgres://postgres:123456@localhost:5432/e2e-test"
